# based on the latest ubuntu
FROM ubuntu:latest
# Update APT using apt-get update
RUN apt-get update
# Upgrade currently installed software through APT using apt-get upgrade -y
RUN apt-get upgrade -y
# Once built, you can run the Docker image in a container and it will echo “Hello, World!” on the terminal.
CMD ["echo", "Hello, World!"]